### PR TITLE
fix: should set title correct

### PR DESCRIPTION
**Pull request by atian25**
##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

##### Description of change

https://github.com/eggjs/egg/issues/1353

### CODE REVIEW

**Comment by popomore** [comment]
没开 codecov？

**Comment by atian25** [comment]
@popomore  codecov 怎么配的? 不是 eggjs group 的?

**Comment by atian25** [comment]
我配了个全局的，之前好像没 config

**Comment by atian25** [comment]
1.1.1

**Pull request merged**
